[[TulipIndicators]]
arch = "aarch64"
git-tree-sha1 = "ed5efb6e241a10bcde4affa56348b62c99438f63"
os = "macos"

    [[TulipIndicators.download]]
    sha256 = "b12d1bbce43bf6e274dc86c29a570e909d5c56f5a6d414f6348fb971e3846525"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.aarch64-apple-darwin.tar.gz"
[[TulipIndicators]]
arch = "aarch64"
git-tree-sha1 = "9990a8c1c60020676e4ad3bdfcd9a31fde9c1cf2"
libc = "glibc"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "81b3a0dd3b38fd2cbb93d219748f4d10229f91a2a042be97540f6b3d04c1c55f"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.aarch64-linux-gnu.tar.gz"
[[TulipIndicators]]
arch = "aarch64"
git-tree-sha1 = "de99267718925bb4d2f2e11a42db3d4b53b72296"
libc = "musl"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "0e3997f7c37c39ba6dbce4be7418fe323b719e8e006be38cd53fe9960ac0d1c7"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.aarch64-linux-musl.tar.gz"
[[TulipIndicators]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d973b64ea8a17f7369eeac953e4fae3c018baeb8"
libc = "glibc"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "eeb91296a598916584614b1263dcc696f9857ed0bb1089ab3649812de9456c14"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.armv6l-linux-gnueabihf.tar.gz"
[[TulipIndicators]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a4594740d2d2a53e07699c76cf7e698de3407eca"
libc = "musl"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "8ac4ec94bf1ebe2c5fd2b7c0973d3b796bf016c4a7f2ad14094e3c4941d29e43"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.armv6l-linux-musleabihf.tar.gz"
[[TulipIndicators]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e11b1deb0c2a9d555b7c5088bd23638ca8a4fbc3"
libc = "glibc"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "8f4112e8e255dff92393c47ff6bd597c6d28789627092b5c4c6a7b7170cde931"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.armv7l-linux-gnueabihf.tar.gz"
[[TulipIndicators]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b66e8b4cc17ef894a798c07b4848fd99a91de2fe"
libc = "musl"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "6b1ffe59865009d7ccee5a0b70f91d9f0586cf8a5df8ae1210fb6bc9f276f535"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.armv7l-linux-musleabihf.tar.gz"
[[TulipIndicators]]
arch = "i686"
git-tree-sha1 = "e0051dcb9d814c975ebc1d4b7e73004513cd8b0c"
libc = "glibc"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "ed940d6f7d66d5d274a0bbe6ce2c24c2ebbcc90f69b27538506b2da8430e4309"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.i686-linux-gnu.tar.gz"
[[TulipIndicators]]
arch = "i686"
git-tree-sha1 = "a98e3f71b783b4e2fa56f52a62b84ab815627317"
libc = "musl"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "29ff8e6abdbc19899cb6a4bf0c3aa1cc72741c38c02cd6f86173d60eac702570"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.i686-linux-musl.tar.gz"
[[TulipIndicators]]
arch = "i686"
git-tree-sha1 = "72de62a6165c1ed3c4ac3eeb4f47bcef820b4159"
os = "windows"

    [[TulipIndicators.download]]
    sha256 = "f74ff14611cce331582d777e7f2477c5d8bfa407b0c1fc05a24b1f706ab29378"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.i686-w64-mingw32.tar.gz"
[[TulipIndicators]]
arch = "powerpc64le"
git-tree-sha1 = "972a8b1d96431977b863e23ef15f198b3c752083"
libc = "glibc"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "c6351249abfd29f71c7a4affc67f2b2509df7ff141881ec68c9fabf140852ca5"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.powerpc64le-linux-gnu.tar.gz"
[[TulipIndicators]]
arch = "x86_64"
git-tree-sha1 = "b4200a5e4daf05fdbe4bf8b600e99c3ad5eb6b6f"
os = "macos"

    [[TulipIndicators.download]]
    sha256 = "cc097edfc6e30d4bd5d407fb7cdf3dec3f4b94dc82c734cb17937bc598fcee8e"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.x86_64-apple-darwin.tar.gz"
[[TulipIndicators]]
arch = "x86_64"
git-tree-sha1 = "510f9de8ffe6ccd0792faab9c8db2c5519573a3e"
libc = "glibc"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "3f5576955371c6178b9d7998c9a60fedef2e9680200e161faf70b08a745d1259"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.x86_64-linux-gnu.tar.gz"
[[TulipIndicators]]
arch = "x86_64"
git-tree-sha1 = "795fc3f1c0911371ad69483c84159fa10ca9bc7c"
libc = "musl"
os = "linux"

    [[TulipIndicators.download]]
    sha256 = "6e3acbc25c9bd036653537d52a352c42ff38e1efb4e01bb0e618ef5606d59e44"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.x86_64-linux-musl.tar.gz"
[[TulipIndicators]]
arch = "x86_64"
git-tree-sha1 = "9f3c3edf09c43e4637e8318f84c756c647e6bdd6"
os = "freebsd"

    [[TulipIndicators.download]]
    sha256 = "d4e45ec0b309fd9e14c8ea6cada572e3e7247fd0eb856a4f6684f0e24a5335af"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.x86_64-unknown-freebsd.tar.gz"
[[TulipIndicators]]
arch = "x86_64"
git-tree-sha1 = "8dfb419e10cf44853ca45c35107f84c572407b26"
os = "windows"

    [[TulipIndicators.download]]
    sha256 = "f13dac401d4d82538aca8be10b02fa967a4743f31c5cb34f46f48a6c417213c2"
    url = "https://github.com/JuliaBinaryWrappers/TulipIndicators_jll.jl/releases/download/TulipIndicators-v0.9.1+0/TulipIndicators.v0.9.1.x86_64-w64-mingw32.tar.gz"
