# Autogenerated wrapper script for TulipIndicators_jll for aarch64-linux-musl
export candles_h, indicators_h, libindicators

JLLWrappers.@generate_wrapper_header("TulipIndicators")
JLLWrappers.@declare_file_product(candles_h)
JLLWrappers.@declare_file_product(indicators_h)
JLLWrappers.@declare_library_product(libindicators, "libindicators.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        candles_h,
        "include/candles.h",
    )

    JLLWrappers.@init_file_product(
        indicators_h,
        "include/indicators.h",
    )

    JLLWrappers.@init_library_product(
        libindicators,
        "lib/libindicators.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
